DROP TABLE IF EXISTS DBS_ORDERS_TB;
 
CREATE TABLE DBS_ORDERS_TB (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  customer_name VARCHAR(250) NOT NULL,
  order_date Date NOT NULL,
  shipping_address NOT NULL,
  order_items VARCHAR(500) NOT NULL,
  order_amount DOUBLE(12,2)
);

DROP TABLE IF EXISTS DBS_ORDER_ITEMS_TB;
 
CREATE TABLE DBS_ORDER_ITEMS_TB (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  product_code VARCHAR(50) NOT NULL,
  product_name VARCHAR(250) NOT NULL,
  quantity INT(3)
);